Auth service, login flow with password confirmation & password reset
Skookum/stumbl-2019 pull request #78
Opened 2019-09-10 19:22 UTC by drewfitz10

## Description

- optimized the api service call to `getAllVenues`. It now occurs once in the App.vue on mount and passed as props to subsequent screen that need the venues. This reduced the calls to the api `/locations` from 4 to 1

- Create auth services with needed api requests. Created Vue mixin to call this globally
- Added validation and error states for all forms
- New views added for the password confirmation & password reset
- added protected routes middleware in router so only the intro, password reset, and account confirmation screen are accessible without being logged in
- 

## Related Issue

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.

2019-09-11 03:01 UTC, prowe214 approved these changes
This looks great.  Huuuuuge bottle of champagne to you bud 🍾 

![thank you](https://media1.giphy.com/media/u0bQN6bxXweHe/source.gif)

2019-09-11 03:01 UTC, prowe214 commented on src/components/map-container/map-container-component.vue
> +    // This is used on initial page load while the API is still fetching the venues
i wasn't aware of `$watch`, cool!

2019-09-11 03:01 UTC, prowe214 commented on src/components/onboarding/email/enter-email-component.vue
> +  public $auth: any;
this `any` is safe 👍

2019-09-11 03:01 UTC, prowe214 commented on src/components/onboarding/email/enter-email-component.vue
> +  get formError() {
probably should be named `formValid`

2019-09-11 03:01 UTC, prowe214 commented on src/components/onboarding/email/enter-email-component.vue
> +    const result = this.$auth.recovery({
glad you took this task, I wasn't aware of `$auth.recovery`

2019-09-11 03:01 UTC, prowe214 commented on src/views/confirmation/confirmation.vue
> +  public $auth: any;
this `any` is safe 👍

2019-09-11 03:01 UTC, prowe214 commented on src/views/recovery/recovery.vue
> +  public $auth: any;
this `any` is also safe 👍

2019-09-11 03:21 UTC, drewfitz10 commented on src/components/onboarding/email/enter-email-component.vue
> +  get formError() {
update made

2019-09-11 03:47 UTC, drey-stepanyuk requested changes
Looks good, just one question and also add margin between the email/password input fields when registering. It's currently smushed together.

2019-09-11 03:47 UTC, drey-stepanyuk commented on src/components/map-container/map-container-component.vue
> +    if (!!this.allVenues.length) {
Why do we need the truthy value from this, can't we just check `this.allVenues.length > 0` ?

2019-09-11 04:23 UTC, drewfitz10 commented on src/components/map-container/map-container-component.vue
> +    if (!!this.allVenues.length) {
We can, both operations do the same thing. Updated it to be `.length > 0`. Also pushed updated the spacing on the inputs

2019-09-12 00:11 UTC, drey-stepanyuk approved these changes

2019-09-12 00:11 UTC, drey-stepanyuk commented
Sorry it took a while to approve this, I forgot to do it :(

2019-09-12 03:19 UTC, merged